#server:
#  port: 2000
#
#spring:
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"
#    listener:
#      simple:
#        concurrency: 1
#        max-concurrency: 1
#        prefetch: 1
#
##server:
##  port: 5000
##
##spring:
##  data:
##    mongodb:
##      uri: mongodb+srv://Dalia:hgdw-09123@cluster0.wtjb5.mongodb.net/userMS?retryWrites=true&w=majority
#
##