server:
  port: 1000

jwt:
  secret: javainuse


spring:
  datasource:
    username: postgres
    password: 12345
    url: jdbc:postgresql://localhost:5432/student
    platform: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  cache:
    type: redis
    redis:
      cache-null-values: true


logging:
  level:
    org:
      springframework:
        cache: Trace