server:
  port: 5000

spring:
  data:
    mongodb:
      uri: mongodb+srv://dalia:hgdw-09123@user.taiu3.mongodb.net/userPostInteraction?retryWrites=true&w=majority
#      uri:mongosh mongodb+srv://monica:1234@cluster0.wkqac.mongodb.net/myFirstDatabase?retryWrites=true&w=majority