version: '2'

services:
  app:
    image: 'redis-docker:latest'
    build:
      context: .
    container_name: redis
    ports:
      - "1000:1000"
    depends_on:
      - redis

  redis:
    image: redis
    #    contain: redis
    ports:
      - "6379:6379"
#    volumes:
#      - ./redis.conf:/src/main/java/guc/bttsBtngan/authentication/config/JavaRedisConfig.java




networks:
  app:
    driver: bridge
  redis:
    driver : bridge
